name: Validate
on: [push]

jobs:
    validate-terraform:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ${{ env.tf_actions_working_dir }}
        steps:
            - uses: hashicorp/setup-terraform@v2
            - name: Terraform fmt
              id: fmt
              run: terraform fmt -check
              continue-on-error: false
            - name: Terraform Init
              id: init
              run: terraform init
            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color